# Generated by Django 3.2.6 on 2021-08-12 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, null=True)),
                ('tel1', models.TextField(max_length=40, null=True)),
                ('add1', models.TextField(max_length=255, null=True)),
                ('add2', models.TextField(max_length=255, null=True)),
                ('opening', models.TextField(max_length=40, null=True)),
                ('off', models.TextField(max_length=40, null=True)),
                ('sit', models.TextField(max_length=40, null=True)),
                ('alcohol', models.TextField(max_length=40, null=True)),
                ('smoke', models.TextField(max_length=40, null=True)),
                ('reservation', models.TextField(max_length=40, null=True)),
                ('restroom', models.TextField(max_length=40, null=True)),
                ('delivery', models.TextField(max_length=40, null=True)),
                ('ballet', models.TextField(max_length=40, null=True)),
                ('introduce', models.TextField(max_length=255, null=True)),
                ('hit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CafeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, null=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='CafeApp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=255, null=True)),
                ('theme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_id', to='CafeApp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=40, null=True)),
                ('score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_id', to='CafeApp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=40, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='CafeApp.cafe')),
            ],
        ),
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='CafeApp.cafe')),
            ],
        ),
    ]
